### ISSUE TITLE
https://www.demo.cn//index.php?m=ke

### ISSUE THREAD

**Issue by pianchi** [inhere/php-srouter#9]
`https://www.demo.cn//index.php?m=ke`
这样的地址将出现错误，如何解决。

```
[15-May-2020 11:54:27 Asia/Shanghai] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Inhere\Route\Router::match() must be of the type string, null given, called in /www/wwwroot/php.cn/vendor/inhere/sroute/src/Dispatcher/SimpleDispatcher.php on line 136 and defined in /www/wwwroot/php.cn/vendor/inhere/sroute/src/Router.php:383
Stack trace:
#0 /www/wwwroot/php.cn/vendor/inhere/sroute/src/Dispatcher/SimpleDispatcher.php(136): Inhere\Route\Router->match(NULL, 'GET')
#1 /www/wwwroot/php.cn/vendor/inhere/sroute/src/Router.php(555): Inhere\Route\Dispatcher\SimpleDispatcher->dispatchUri(NULL, 'GET')
#2 /www/wwwroot/php.cn/index.php(62): Inhere\Route\Router->dispatch()
#3 {main}
thrown in /www/wwwroot/php.cn/vendor/inhere/sroute/src/Router.php on line 383
```

**Comment by inhere** [comment]
我更新个版本修复下。

**Comment by inhere** [comment]
你更新版本 再看看
